name: smarthjelp_app
description: SmartHjelp MVP app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # STATE
  provider: ^6.1.2

  # UTIL
  uuid: ^4.3.3
  intl: ^0.20.2

  # UI
  google_fonts: ^8.0.2

  # MAP
  google_maps_flutter: ^2.6.0

  # IMAGE (beholder denne for mobil senere)
  image_picker: ^1.0.7

  # 🔥 FIX – WEB/PC FILE PICKER
  file_picker: ^6.1.1

  # STORAGE / PREFS
  shared_preferences: ^2.5.5

  # LOCATION
  geolocator: ^14.0.2

  # NOTIFICATIONS (fremtid)
  flutter_local_notifications: ^21.0.0
  firebase_core: ^4.6.0
  firebase_messaging: ^16.1.3

  # EXPORT SYSTEM
  excel: ^4.0.6
  share_plus: ^10.1.2

  # BACKEND
  supabase_flutter: ^2.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true